feat: display memory eviction policy in redis admin widget
blomstra/flarum-ext-horizon pull request #20
Opened 2024-05-20 11:52 UTC by imorland

For example:

![image](https://github.com/blomstra/flarum-ext-horizon/assets/16573496/bba3c729-714a-4c6c-a948-121fc625d8e4)

or

![image](https://github.com/blomstra/flarum-ext-horizon/assets/16573496/24d2dc34-127d-4e96-a98b-daa5ccf4d4aa)

etc

2024-05-21 12:49 UTC, luceos commented
Although I can understand where this comes from. I am worried that the widgets in the admin are steering towards an expert mode instead of providing noob-friendly information.

Maybe this information would make more sense in the dashboard when they would be translated towards a human readable form?

2024-05-24 08:56 UTC, imorland commented
One could argue that `Horizon` is already an expert setup, rather than for noobs, but nonetheless, I have added a tooltip to the widget, which gives a brief explanation, as well as a [link to the official Redis documentation for data eviction policy](https://redis.io/docs/latest/develop/reference/eviction/)

![image](https://github.com/blomstra/flarum-ext-horizon/assets/16573496/0b5e58bb-4ac4-4965-bb5a-0d450475be3e)

2024-05-24 09:48 UTC, luceos requested changes

2024-05-24 09:48 UTC, luceos commented on js/src/admin/components/HorizonStatsWidget.tsx
> +    return items;
This seems to be code that is not used in the PR, was this added by mistake?

2024-05-24 10:03 UTC, imorland commented on js/src/admin/components/HorizonStatsWidget.tsx
> +    return items;
Please look again, this code is used to construct the widget title labels (ie if a `infoLabel` and `infoUrl` are passed, the tooltip and `i` icon are then added).

It also lays the foundation of making it possible to extend and add additional widgets to the queue status from other extensions (although this is not exported yet, but it is a start)

2024-05-24 10:30 UTC, luceos commented on js/src/admin/components/HorizonStatsWidget.tsx
> +    return items;
Ah yea I see 👍

2024-05-24 10:31 UTC, merged